import type { LucideIcon } from "lucide-react"
import {
    ArrowRightLeft,
    BadgeDollarSign,
    Binary,
    Braces,
    CalendarDays,
    Calculator,
    CaseSensitive,
    Code2,
    DollarSign,
    FileCode2,
    FileDigit,
    FileImage,
    FileJson,
    FileLock2,
    FileOutput,
    FilePenLine,
    FileSymlink,
    FileText,
    FileType,
    FileVideo,
    GitCompare,
    Globe2,
    Hash,
    Image,
    ImageDown,
    ImageMinus,
    ImagePlus,
    KeyRound,
    Link,
    Percent,
    Pipette,
    QrCode,
    Regex,
    Scaling,
    ScanText,
    ShieldCheck,
    Timer,
    Type,
    UserRoundCog,
    Utensils,
    Video,
    Wrench,
} from "lucide-react"

export const toolIcons = {
    "age-calculator": CalendarDays,
    "base64-converter": Binary,
    "case-converter": CaseSensitive,
    "color-picker": Pipette,
    "csv-to-json": FileJson,
    "currency-converter": DollarSign,
    "data-uri-generator": FileSymlink,
    "favicon-generator": ImagePlus,
    "file-converter": FileOutput,
    "file-encryptor": FileLock2,
    "file-rename-tool": FilePenLine,
    "hash-generator": Hash,
    "image-compressor": ImageDown,
    "image-resizer": Scaling,
    "image-to-svg": FileType,
    "json-formatter": Braces,
    "jwt-debugger": KeyRound,
    "lorem-ipsum-generator": Type,
    "markdown-previewer": FileText,
    "mp4-to-gif": FileVideo,
    "nutrition-master": Utensils,
    "password-generator": KeyRound,
    "pdf-image-extractor": FileImage,
    "percentage-calculator": Percent,
    "profile-pic-optimizer": UserRoundCog,
    "qr-code-tool": QrCode,
    "regex-generator": Regex,
    "remove-background": ImageMinus,
    "ssl-checker": ShieldCheck,
    "svg-converter": FileCode2,
    "text-diff-checker": GitCompare,
    "text-extractor": ScanText,
    "time-calculator": Timer,
    "unit-converter": ArrowRightLeft,
    "url-encoder": Link,
    "video-thumbnail-generator": Video,
    "website-cost-calculator": BadgeDollarSign,
    "word-counter": FileDigit,
    "xml-formatter": FileCode2,
} satisfies Record<string, LucideIcon>

export const categoryIcons = {
    image: Image,
    text: Type,
    developer: Code2,
    file: FileText,
    security: ShieldCheck,
    web: Globe2,
    finance: Calculator,
    misc: Wrench,
} satisfies Record<string, LucideIcon>

export function getToolIcon(slug: string): LucideIcon {
    return toolIcons[slug as keyof typeof toolIcons] ?? Wrench
}

export function hasToolIcon(slug: string): boolean {
    return slug in toolIcons
}
